# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :test, :development do
  gem 'babosa', '~> 2.0'
  gem 'liquid', '~> 5.5', '>= 5.5.1'

  gem 'dotenv', '~> 3.1', '>= 3.1.4'

  gem 'rspec', '~> 3.13'

  gem 'rubocop', '~> 1.66', '>= 1.66.1'
  gem 'rubocop-rspec', '~> 3.0', '>= 3.0.5'

  gem 'pry-byebug', '~> 3.10', '>= 3.10.1'
end
